cmake_minimum_required(VERSION 3.26)
project(strukturno)

set(CMAKE_CXX_STANDARD 20)

add_executable(strukturno main.cpp)
add_executable(palindrom palindrom.cpp)
add_executable(duplikati duplikati.cpp)
add_executable(a matrici.cpp
        sentence.cpp)
add_executable(v labs.cpp)
add_executable(y string.cpp)
add_executable(d vezbanje.cpp)
add_executable(c rekurzija.cpp)
add_executable(b funkcii.cpp)
add_executable(sovrsheni sovrsheni.cpp)
